name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploying code over SSH
      uses: appleboy/ssh-action@master
      with:
        host: cicd.shubhamjoshi.tech
        username: azureuser
        key: ${{secrets.ONEPAGECV_SECRET}}
        port: 22
        script: |
          cd /var/www/html/onepagecv-cicd/
          git pull origin main
          git status
