name: SSH Deploy
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      name: test onepagecv deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: cicd.shubhamjoshi.tech
        username: azureuser
        key: ${{secrets.ONEPAGECV_SECRET}}
        port: 22
        script: |
          cd /var/www/html/onepagecv-cicd/
          git pull origin main
          git status
